name: Sonarcloud Scan

on:
  workflow_run:
    workflows: [ "Check, Build and Test" ]
    types: [ completed ]

jobs:
  sonar:
    runs-on: ubuntu-latest
    container: docker.io/ogdf/clang:15
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Install sonar-scanner
        uses: SonarSource/sonarcloud-github-c-cpp@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: |
          echo "{\"github\": $GITHUB_CONTEXT, \"steps\": $STEPS_CONTEXT, \"runner\": $RUNNER_CONTEXT, \"strategy\": $STRATEGY_CONTEXT}"
          echo
          env

      - name: "Add workspace as a safe directory in containers"
        run: git config --system --add safe.directory $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          repository: ${{ github.event.workflow_run.repository.full_name }}

      - name: Get PR Metadata
        if: github.event.workflow_run.event == 'pull_request'
        id: pr-info
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var fs = require('fs');
            var pr_number = Number(fs.readFileSync('static-analysis/PR-NUMBER'));
            var pr_meta = await github.pulls.get({
              ${{ github.event.workflow_run.repository.owner.login }},
              ${{ github.event.workflow_run.repository.name }},
              pr_number,
            });
            console.log(pr_meta);
            if (github.event.workflow_run.head_commit.id != pr_meta.head.sha) {
              core.setFailed('Triggering workflow commit sha doesn't match claimed PR head commit sha!');
            }
            return pr_meta;
      - name: Dump GitHub context 2
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: |
          echo "{\"github\": $GITHUB_CONTEXT, \"steps\": $STEPS_CONTEXT, \"runner\": $RUNNER_CONTEXT, \"strategy\": $STRATEGY_CONTEXT}"
          echo
          env
      - name: Checkout PR base branch
        if: github.event.workflow_run.event == 'pull_request'
        run: |
          git remote add upstream ${{ github.event.repository.clone_url }}
          git fetch upstream
          git checkout -B ${{ steps.pr-info.outputs.result.base.ref }} upstream/${{ steps.pr-info.outputs.result.base.ref }}
          git checkout ${{ github.event.workflow_run.head_branch }}
          git clean -ffdx && git reset --hard HEAD
          git reset --hard upstream/${{ steps.pr-info.outputs.result.base.ref }} sonar-project.properties

      - name: SonarCloud PR Scan
        if: github.event.workflow_run.event == 'pull_request'
        run: >
          sonar-scanner
          -Dsonar.links.ci=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          -Dsonar.pullrequest.key=${{ steps.pr-info.outputs.result.number }}
          -Dsonar.pullrequest.branch=${{ github.event.workflow_run.head_branch }}
          -Dsonar.pullrequest.base=${{ steps.pr-info.outputs.result.base.ref }}
          -Dproject.settings=sonar-project.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: SonarCloud non-PR Scan
        if: github.event.workflow_run.event != 'pull_request'
        run: >
          sonar-scanner
          -Dsonar.links.ci=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          -Dproject.settings=sonar-project.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
